# Generated by Django 2.2.3 on 2019-07-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ordercode', models.IntegerField()),
                ('customer', models.CharField(max_length=255)),
                ('orderstatus', models.CharField(max_length=50)),
                ('ordershipmentstatus', models.CharField(max_length=40)),
                ('truck', models.CharField(max_length=50)),
                ('areacode', models.IntegerField()),
                ('salesman', models.CharField(max_length=100)),
            ],
        ),
    ]
