# Generated by Django 2.2.3 on 2019-07-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorders',
            name='hostname',
            field=models.CharField(default='0000', max_length=100),
        ),
    ]
